export const ActionTypes = {
  GET_DOGS: "GET_DOGS",
  DOG_DETAILS: "DOG_DETAILS",
  GET_DOGS_BY_NAME: "GET_DOGS_BY_NAME",
  GET_TEMPERAMENTS: "GET_TEMPERAMENTS",
  POST_DOG: "POST_DOG",
  FILTER_BY_TEMPERAMENT: "FILTER_BY_TEMPERAMENT",
  FILTER_DOGS_CREATED: "FILTER_DOGS_CREATED",
  ORDER_BY_NAME: "ORDER_BY_NAME",
  ORDER_BY_WEIGHT: "ORDER_BY_WEIGHT"
};